import {$,$$} from './core/utils.js';import {LABELS} from './config.js';import {state} from './core/state.js';import {recommendedSplit} from './services/personalization.js';import {showScreen,bindTabs} from './ui/router.js';import {initOnboarding,resetOnboarding} from './ui/onboarding.js';import {renderHome,renderBadges} from './ui/home.js';import {initDiscover} from './ui/discover.js';import {renderDaily} from './ui/daily.js';import {renderProfile} from './ui/profile.js';import {initWorkout,startWorkout} from './ui/workout.js';import {showReward} from './ui/reward.js';import {initFeedback,showFeedback} from './ui/feedback.js';import {mountMotionDemo} from './ui/motion-demo.js';import {stopAmbient} from './services/audio.js';import {preloadMedia} from './services/media-resolver.js';import {initSiteAudio} from './services/site-audio.js';
function renderAll(){renderHome();renderDaily();renderProfile();renderBadges()}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>$('#toast').classList.remove('show'),2200)}
initSiteAudio();preloadMedia();bindTabs();initOnboarding();initDiscover();initWorkout();initFeedback();
$('#homeProfile').onclick=()=>showScreen('profile');$('#openBadges').onclick=()=>showScreen('profile');$('#openStats').onclick=()=>showScreen('daily');$('#openStatsProfile').onclick=()=>showScreen('daily');$('#openBadgesProfile').onclick=()=>showScreen('profile');$('#editPlan').onclick=resetOnboarding;$('#editSchedule').onclick=resetOnboarding;
$('#startPlan').onclick=()=>startWorkout(recommendedSplit());$('#dailyStart').onclick=()=>startWorkout(recommendedSplit());$('#rewardClose').onclick=()=>{ $('#rewardModal').classList.add('hidden'); $('#workoutModal').classList.add('hidden'); showScreen('home'); renderAll(); };$('#closeDetail').onclick=()=>$('#detailModal').classList.add('hidden');
window.addEventListener('workout:start',e=>startWorkout(e.detail.split));window.addEventListener('workout:finished',e=>{ stopAmbient();$('#workoutModal').classList.add('hidden'); window.__pendingWorkoutResult=e.detail; renderAll(); showFeedback(e.detail); });window.addEventListener('plan:updated',renderAll);window.addEventListener('toast',e=>toast(e.detail));
window.addEventListener('exercise:detail',async e=>{const ex=window.__EXERCISES?.find(x=>x.id===e.detail.id);if(!ex)return;$('#detailContent').innerHTML=`<div class="detail-media" id="detailMotion"></div><span class="eyebrow">${ex.body}</span><h1>${ex.name}</h1><p>${ex.desc}</p>${ex.mediaNote?`<p class="muted small" style="margin-top:6px">${ex.mediaNote}</p>`:''}<div class="detail-tags"><span>${LABELS.level[ex.level]||ex.level}</span><span>${LABELS.equipment[ex.equipment]||ex.equipment}</span><span>${ex.type==='time'?ex.base+' segundos':ex.base+' repetições'}</span></div><button id="detailStart" class="button primary full">Adicionar ao treino</button>`;mountMotionDemo($('#detailMotion'),ex);$('#detailModal').classList.remove('hidden');$('#detailStart').onclick=()=>{ $('#detailModal').classList.add('hidden');startWorkout('CUSTOM',ex)}});
import('./data/exercises.js').then(m=>{window.__EXERCISES=m.EXERCISES});
if(state.onboard){showScreen('home');renderAll()}else showScreen('onboarding');
