const KEY='ht_state_v3';
const defaults={onboard:false,answers:{goal:'hypertrophy',level:'beginner',equipment:'none',frequency:'3',duration:'20–35 min',focus:'body'},xp:0,streak:0,lastWorkout:null,workouts:0,minutes:0,sets:0,completedDays:[],history:[],progress:{},currentSplit:'A'};
let state=load(); let qIndex=0; let workout=null; let timer=null; let restTimer=null; let selectedFilters={body:'Todos',level:'Todos',equipment:'Todos'};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const labels={goal:{hypertrophy:'Hipertrofia',strength:'Força',calisthenics:'Calistenia',conditioning:'Condicionamento'},level:{beginner:'Iniciante',intermediate:'Intermediário',advanced:'Avançado'},equipment:{none:'Sem equipamentos',basic:'Equipamentos básicos',full:'Equipamentos completos'},focus:{body:'Corpo inteiro',legs:'Pernas e glúteos',upper:'Parte superior',mobility:'Mobilidade'}};
function load(){try{return {...structuredClone(defaults),...JSON.parse(localStorage.getItem(KEY)||'{}'),answers:{...defaults.answers,...(JSON.parse(localStorage.getItem(KEY)||'{}').answers||{})}}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function today(){return new Date().toISOString().slice(0,10)}
function daysBetween(a,b){return Math.floor((new Date(b)-new Date(a))/86400000)}
function renderQuestion(){const q=DATA.questions[qIndex];$('#stepCount').textContent=`${qIndex+1}/${DATA.questions.length}`;$('#obProgress').style.width=`${((qIndex+1)/DATA.questions.length)*100}%`;$('#obTitle').innerHTML=q.title;$('#obSubtitle').textContent=q.sub;$('#question').innerHTML=`<div class="question-grid">${q.options.map((o,i)=>`<button class="question-card ${state.answers[q.key]===valueFor(q.key,o[1])?'active':''}" data-i="${i}"><span class="q-icon">${o[0]}</span><span><b>${o[1]}</b><small>${o[2]}</small></span><span class="check">✓</span></button>`).join('')}</div>`;$$('.question-card').forEach(b=>b.onclick=()=>{state.answers[q.key]=valueFor(q.key,q.options[+b.dataset.i][1]);$$('.question-card').forEach(x=>x.classList.remove('active'));b.classList.add('active')});$('#obBack').hidden=qIndex===0}
function valueFor(k,label){const m={goal:{'Hipertrofia':'hypertrophy','Força':'strength','Calistenia':'calisthenics','Condicionamento':'conditioning'},level:{'Iniciante':'beginner','Intermediário':'intermediate','Avançado':'advanced'},equipment:{'Nenhum':'none','Básicos':'basic','Completos':'full'},frequency:{'2 dias':'2','3 dias':'3','4 dias':'4','5 dias':'5'},duration:{'10–20 min':'10–20 min','20–35 min':'20–35 min','35–50 min':'35–50 min','50+ min':'50+ min'},focus:{'Corpo inteiro':'body','Pernas e glúteos':'legs','Parte superior':'upper','Mobilidade':'mobility'}};return m[k][label]}
function finishOnboarding(){state.onboard=true;save();showScreen('home');renderAll()}
function showScreen(id){$$('.screen').forEach(s=>s.classList.add('hidden'));$('#'+id).classList.remove('hidden');$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===id));if(id==='discover')renderDiscover();if(id==='daily')renderDaily();if(id==='profile')renderProfile()}
function planFor(){const a=state.answers;let p={name:'Construtor de Massa',desc:'Volume, controle e progressão para hipertrofia em casa.'};if(a.goal==='strength')p={name:'Força em Casa',desc:'Progressões focadas em técnica, força e controle.'};if(a.goal==='calisthenics')p={name:'Calistenia Progressiva',desc:'Evolua de variações simples para movimentos mais difíceis.'};if(a.goal==='conditioning')p={name:'Condicionamento em Casa',desc:'Sessões dinâmicas para resistência e preparo físico.'};return p}
function userLevel(){return Math.floor(state.xp/300)+1}
function levelName(){return ['Novato','Constante','Disciplinado','Forte','Elite','Lenda'][Math.min(5,userLevel()-1)]}
function renderHome(){const p=planFor();$('#planName').textContent=p.name;$('#planDescription').textContent=p.desc;$('#planDays').textContent=state.answers.frequency;$('#planMinutes').textContent=(state.answers.duration.match(/\d+/)||['20'])[0];$('#planLevel').textContent=labels.level[state.answers.level];$('#streak').textContent=state.streak;$('#xp').textContent=state.xp;$('#userLevel').textContent=userLevel();$('#levelName').textContent=levelName();const cur=state.xp%300;$('#levelProgress').textContent=`${cur}/300`;$('#levelBar').style.width=`${cur/3}%`;$('#totalWorkouts').textContent=state.workouts;$('#totalMinutes').textContent=state.minutes;$('#totalSets').textContent=state.sets;renderWeek();renderBadges();$('#profileSummary').textContent=`${labels.goal[state.answers.goal]} • ${labels.level[state.answers.level]} • ${labels.equipment[state.answers.equipment]} • ${state.answers.frequency} dias/semana`}
function renderWeek(){const days=Number(state.answers.frequency)||3;const keys=days===2?['FULL','C']:days>=4?['A','B','C','FULL']:['A','B','C'];$('#weekGrid').innerHTML=keys.map((k,i)=>{const d=DATA.splits[k];const done=state.completedDays.includes(k);return `<button class="day-card ${done?'done':''}" data-split="${k}"><span>${done?'✓':String.fromCharCode(65+i)}</span><b>${d.name}</b><small>${d.focus}</small><i>${done?'✓':'▶'}</i></button>`}).join('');$$('.day-card').forEach(b=>b.onclick=()=>startWorkout(b.dataset.split))}
function renderBadges(){const html=DATA.badges.map(b=>{const unlocked=b.need?state.workouts>=b.need:state.sets>=b.sets;return `<div class="badge ${unlocked?'':'locked'}"><span>${b.icon}</span><b>${b.name}</b><small>${b.desc}</small></div>`}).join('');$('#badgeRow').innerHTML=html;$('#allBadges').innerHTML=html}
function compatible(ex){const a=state.answers;const eq=a.equipment;const okEq=ex.equipment==='none'||eq==='full'||(eq==='basic'&&ex.equipment==='basic');const lv={beginner:1,intermediate:2,advanced:3};const okLv=lv[ex.level]<=lv[a.level]+1;return okEq&&okLv}
function difficultyAdjust(ex){const base=ex.base;const lv=state.answers.level;if(ex.type==='time')return Math.max(15,base+(lv==='advanced'?10:lv==='intermediate'?5:0));return Math.max(5,base+(lv==='advanced'?3:lv==='intermediate'?2:0))}
function buildItems(split){let ids=DATA.splits[split]?.ids||DATA.splits.FULL.ids;let chosen=ids.map(id=>DATA.exercises.find(e=>e.id===id)).filter(Boolean).filter(compatible);if(!chosen.length)chosen=DATA.splits.FULL.ids.map(id=>DATA.exercises.find(e=>e.id===id));let warm=['jumping-jack','arm-circles'];let cool=state.answers.focus==='mobility'?['hip-mobility','chest-stretch']:['hip-mobility','quad-stretch'];return [...warm.map(id=>DATA.exercises.find(e=>e.id===id)),...chosen,...cool.map(id=>DATA.exercises.find(e=>e.id===id))].filter(Boolean).map(e=>({...e,target:difficultyAdjust(e)}))}
function startWorkout(split='A'){state.currentSplit=split;const items=buildItems(split);workout={split,items,index:0,set:1,doneReps:0,sessionSets:0,sessionMinutes:0,started:Date.now(),rest:false};$('#workoutModal').classList.remove('hidden');renderExercise()}
function renderExercise(){clearInterval(timer);clearInterval(restTimer);workout.rest=false;const e=workout.items[workout.index], warm=workout.index<2,cool=workout.index>=workout.items.length-2;$('#wmCounter').textContent=`${workout.index+1}/${workout.items.length}`;$('#wmWorkoutName').textContent=DATA.splits[workout.split]?.name||'Treino';$('#wmProgress').style.width=`${((workout.index+1)/workout.items.length)*100}%`;$('#wmType').textContent=warm?'AQUECIMENTO':cool?'RESFRIAMENTO':`TREINO ${workout.split}`;$('#wmTitle').textContent=e.name;$('#wmSub').textContent=e.desc;$('#setLabel').textContent=e.sets===1?'PREPARAÇÃO':`SÉRIE ${workout.set} DE ${e.sets}`;$('#wmTarget').textContent=e.type==='time'?`${e.target} segundos`:`${e.target} repetições`;$('#repCounter').classList.toggle('hidden',e.type==='time');$('#timer').classList.toggle('hidden',e.type!=='time');$('#restBox').classList.add('hidden');$('#repGoal').textContent=e.type==='reps'?e.target:0;$('#repDone').textContent=0;$('#wmNext').textContent=e.type==='time'?'Concluir tempo →':workout.set<e.sets?'Concluir série →':'Concluir exercício →';$('#replaceExercise').style.display=(warm||cool)?'none':'block';renderMedia(e);if(e.type==='time')startHold(e.target)}
function renderMedia(e){const box=$('#mediaBox');if(e.media){box.innerHTML=`<img src="${e.media}" alt="Demonstração de ${esc(e.name)}" onerror="this.remove();this.parentElement.classList.add('fallback')">`}else box.innerHTML=`<div class="motion"><span class="stick head"></span><span class="stick body"></span><span class="stick arm a1"></span><span class="stick arm a2"></span><span class="stick leg l1"></span><span class="stick leg l2"></span></div><small>Demonstração visual</small>`}
function startHold(seconds){let n=seconds;$('#timer').textContent=fmt(n);timer=setInterval(()=>{n--;$('#timer').textContent=fmt(Math.max(n,0));if(n<=0){clearInterval(timer);$('#wmNext').textContent='Avançar →'}},1000)}
function fmt(n){return `00:${String(Math.max(0,n)).padStart(2,'0')}`}
function nextWorkoutStep(){const e=workout.items[workout.index];if(e.type==='reps'){if(workout.doneReps<e.target){return; } }else{if($('#timer').classList.contains('hidden')===false&&$('#timer').textContent!=='00:00'&&$('#wmNext').textContent.startsWith('Concluir'))return}
workout.sessionSets++;state.sets++;workout.doneReps=0;if(workout.set<e.sets){workout.set++;save();showRest(e.rest);return}workout.index++;workout.set=1;if(workout.index>=workout.items.length){completeWorkout();return}showRest(e.rest)}
function showRest(seconds){if(!seconds){renderExercise();return}workout.rest=true;$('#restBox').classList.remove('hidden');$('#repCounter').classList.add('hidden');$('#timer').classList.add('hidden');$('#wmNext').disabled=true;let n=seconds;$('#restTimer').textContent=fmt(n);clearInterval(restTimer);restTimer=setInterval(()=>{n--;$('#restTimer').textContent=fmt(Math.max(n,0));if(n<=0){clearInterval(restTimer);$('#restBox').classList.add('hidden');$('#wmNext').disabled=false;renderExercise()}},1000)}
function addRep(delta){const e=workout.items[workout.index];if(e.type!=='reps')return;workout.doneReps=Math.max(0,Math.min(e.target,workout.doneReps+delta));$('#repDone').textContent=workout.doneReps}
function replaceExercise(){const current=workout.items[workout.index];const pool=DATA.exercises.filter(e=>e.body===current.body&&e.id!==current.id&&compatible(e));if(!pool.length)return;const next=pool[Math.floor(Math.random()*pool.length)];workout.items[workout.index]={...next,target:difficultyAdjust(next)};workout.set=1;renderExercise()}
function skipExercise(){workout.index++;workout.set=1;if(workout.index>=workout.items.length)completeWorkout();else renderExercise()}
function completeWorkout(){clearInterval(timer);clearInterval(restTimer);$('#workoutModal').classList.add('hidden');const mins=Math.max(5,Math.round((Date.now()-workout.started)/60000));const xp=80+workout.sessionSets*10;state.workouts++;state.minutes+=mins;state.sets+=0;state.xp+=xp;const t=today();if(state.lastWorkout===t){}else if(state.lastWorkout&&daysBetween(state.lastWorkout,t)===1)state.streak++;else state.streak=1;state.lastWorkout=t;if(!state.completedDays.includes(workout.split))state.completedDays.push(workout.split);state.history.unshift({date:t,split:workout.split,name:DATA.splits[workout.split]?.name||'Treino',minutes:mins,sets:workout.sessionSets,xp});state.history=state.history.slice(0,30);save();renderAll();const badge=DATA.badges.find(b=>((b.need&&state.workouts===b.need)||(b.sets&&state.sets===b.sets)));$('#rewardXP').textContent=`+${xp}`;$('#rewardSets').textContent=workout.sessionSets;$('#rewardMinutes').textContent=mins;$('#rewardTitle').textContent=state.workouts===1?'Primeiro treino concluído!':'Mais um treino concluído!';$('#rewardText').textContent=`Sequência atual: ${state.streak} dia${state.streak===1?'':'s'}. Nível ${userLevel()} — ${levelName()}.`;$('#rewardIcon').textContent=state.streak>=7?'🏆':'🔥';$('#newBadge').classList.toggle('hidden',!badge);if(badge)$('#newBadge').innerHTML=`<b>${badge.icon} ${badge.name}</b><small>Conquista desbloqueada!</small>`;$('#rewardModal').classList.remove('hidden')}
function renderDiscover(){const bodies=['Todos','Peito','Costas','Ombros','Braços','Pernas','Glúteos','Core','Cardio','Mobilidade'];$('#categoryRow').innerHTML=bodies.map(x=>`<button class="chip ${selectedFilters.body===x?'active':''}" data-body="${x}">${x}</button>`).join('');const filters=['Todos','Iniciante','Intermediário','Avançado','Sem equipamentos','Básicos','Completos'];$('#filterRow').innerHTML=filters.map(x=>`<button class="chip ${selectedFilters.level===x||selectedFilters.equipment===x?'active':''}" data-filter="${x}">${x}</button>`).join('');$$('[data-body]').forEach(b=>b.onclick=()=>{selectedFilters.body=b.dataset.body;renderDiscover()});$$('[data-filter]').forEach(b=>b.onclick=()=>{const x=b.dataset.filter;if(['Iniciante','Intermediário','Avançado'].includes(x)){selectedFilters.level=x;selectedFilters.equipment='Todos'}else if(['Sem equipamentos','Básicos','Completos'].includes(x)){selectedFilters.equipment=x;selectedFilters.level='Todos'}else{selectedFilters.level='Todos';selectedFilters.equipment='Todos'}renderDiscover()});const q=($('#searchInput')?.value||'').toLowerCase();const lvl={Iniciante:'beginner',Intermediário:'intermediate',Avançado:'advanced'};const eq={'Sem equipamentos':'none','Básicos':'basic','Completos':'full'};const list=DATA.exercises.filter(e=>(selectedFilters.body==='Todos'||e.body===selectedFilters.body)&&(selectedFilters.level==='Todos'||e.level===lvl[selectedFilters.level])&&(selectedFilters.equipment==='Todos'||e.equipment===eq[selectedFilters.equipment])&&(!q||`${e.name} ${e.body} ${e.target}`.toLowerCase().includes(q)));$('#resultCount').textContent=`${list.length} resultados`;$('#exerciseGrid').innerHTML=list.map(e=>`<button class="exercise-card" data-ex="${e.id}"><div class="thumb">${e.media?`<img src="${e.media}" alt="">`:'<span>↗</span>'}</div><div><b>${esc(e.name)}</b><small>${e.body} • ${e.type==='time'?e.base+'s':e.base+' reps'} • ${labels.level[e.level]}</small></div></button>`).join('');$$('.exercise-card').forEach(b=>b.onclick=()=>openDetail(DATA.exercises.find(e=>e.id===b.dataset.ex)))}
function openDetail(e){if(!e)return;$('#detailContent').innerHTML=`<div class="detail-media">${e.media?`<img src="${e.media}">`:'<div class="motion big"></div>'}</div><div class="eyebrow">${e.body}</div><h1>${esc(e.name)}</h1><p>${esc(e.desc)}</p><div class="detail-tags"><span>${labels.level[e.level]}</span><span>${labels.equipment[e.equipment]}</span><span>${e.type==='time'?e.base+' segundos':e.base+' repetições'}</span></div><button class="primary full" id="detailStart">Adicionar ao treino</button>`;$('#detailModal').classList.remove('hidden');$('#detailStart').onclick=()=>{$('#detailModal').classList.add('hidden');state.currentSplit='CUSTOM';startCustom(e)}}
function startCustom(e){workout={split:'CUSTOM',items:[{...e,target:difficultyAdjust(e),sets:e.sets}],index:0,set:1,doneReps:0,sessionSets:0,started:Date.now()};$('#workoutModal').classList.remove('hidden');renderExercise()}
function renderDaily(){const d=new Date();const days=[];for(let i=-2;i<=4;i++){const x=new Date(d);x.setDate(d.getDate()+i);const iso=x.toISOString().slice(0,10);days.push(`<div class="date ${iso===today()?'active':''} ${state.history.some(h=>h.date===iso)?'done':''}"><small>${x.toLocaleDateString('pt-BR',{weekday:'short'}).replace('.','')}</small><b>${x.getDate()}</b></div>`)}$('#dateStrip').innerHTML=days.join('');$('#dailyStreak').textContent=state.streak;$('#dailyMessage').textContent=state.lastWorkout===today()?'Treino feito hoje. Você manteve o ritmo!':'Cada treino conta. O próximo começa com um toque.';const todayHist=state.history.filter(h=>h.date===today());const mins=todayHist.reduce((a,h)=>a+h.minutes,0);const sets=todayHist.reduce((a,h)=>a+h.sets,0);const xp=todayHist.reduce((a,h)=>a+h.xp,0);$('#dailyMinutes').textContent=mins;$('#todayStatus').textContent=`${mins} min`;$('#dailyXP').textContent=xp;$('#dailySets').textContent=sets;$('#history').innerHTML=state.history.length?state.history.slice(0,10).map(h=>`<div class="history-item"><span>🔥</span><div><b>${h.name}</b><small>${formatDate(h.date)} • ${h.sets} séries • ${h.minutes} min</small></div><strong>+${h.xp}</strong></div>`).join(''):'<div class="empty">Seu histórico aparecerá aqui após o primeiro treino.</div>'}
function formatDate(x){return new Date(x+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short'}).replace('.','')}
function renderProfile(){renderBadges();$('#profileSummary').textContent=`${labels.goal[state.answers.goal]} • ${labels.level[state.answers.level]} • ${labels.equipment[state.answers.equipment]} • ${state.answers.frequency} dias/semana`}
function renderAll(){renderHome();renderDaily();renderProfile()}
$('#nextQuestion').onclick=()=>{if(qIndex<DATA.questions.length-1){qIndex++;renderQuestion()}else finishOnboarding()};$('#obBack').onclick=()=>{if(qIndex>0){qIndex--;renderQuestion()}};$('#skipOnboarding').onclick=finishOnboarding;
$('#startPlan').onclick=()=>startWorkout('A');$('#dailyStart').onclick=()=>startWorkout(Number(state.answers.frequency)===2?'FULL':'A');$('#wmPause')?.remove();$('#repMinus').onclick=()=>addRep(-1);$('#repPlus').onclick=()=>addRep(1);$('#wmNext').onclick=nextWorkoutStep;$('#replaceExercise').onclick=replaceExercise;$('#skipExercise').onclick=skipExercise;$('#skipRest').onclick=()=>{clearInterval(restTimer);$('#restBox').classList.add('hidden');$('#wmNext').disabled=false;renderExercise()};$('#closeWorkout').onclick=()=>{clearInterval(timer);clearInterval(restTimer);$('#workoutModal').classList.add('hidden')};$('#rewardClose').onclick=()=>$('#rewardModal').classList.add('hidden');$('#closeDetail').onclick=()=>$('#detailModal').classList.add('hidden');
$('#editPlan').onclick=()=>{$('#profile').classList.add('hidden');state.onboard=false;save();qIndex=0;showScreen('onboarding');renderQuestion()};$('#openProfile').onclick=()=>showScreen('profile');$('#openBadges').onclick=()=>showScreen('profile');$('#openBadges2').onclick=()=>showScreen('profile');$('#openStats').onclick=()=>showScreen('daily');$('#openStats2').onclick=()=>showScreen('daily');$('#openSchedule').onclick=()=>{$('#editPlan').click()};$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='home-training-progresso.json';a.click();URL.revokeObjectURL(a.href)};$('#resetData').onclick=()=>{if(confirm('Reiniciar todo o progresso?')){localStorage.removeItem(KEY);location.reload()}};
$$('.tab').forEach(t=>t.onclick=()=>showScreen(t.dataset.tab));$('#searchInput').addEventListener('input',renderDiscover);
if(state.onboard){showScreen('home');renderAll()}else{showScreen('onboarding');renderQuestion()}
