import {EXERCISES} from '../data/exercises.js';import {LABELS} from '../config.js';import {$,$$,escapeHTML} from '../core/utils.js';import {compatible,targetFor} from '../services/personalization.js';import {progressLabel} from '../services/progression.js';import {resolveMediaCandidates} from '../services/media-resolver.js';
let filters={body:'Todos',level:'Todos',equipment:'Todos'};
const levelMap={Iniciante:'beginner',Intermediário:'intermediate',Avançado:'advanced'};const eqMap={'Sem equipamentos':'none',Mochila:'backpack',Cadeira:'chair',Elástico:'band',Halteres:'dumbbell','Barra fixa':'bar'};
export async function renderDiscover(){const bodies=['Todos','Peito','Costas','Ombros','Bíceps','Tríceps','Pernas','Glúteos','Posteriores','Panturrilhas','Core','HIIT','Mobilidade'];const levels=['Todos','Iniciante','Intermediário','Avançado'];const equipment=['Todos','Sem equipamentos','Mochila','Cadeira','Elástico','Halteres','Barra fixa'];renderChips('#bodyFilters',bodies,'body');renderChips('#levelFilters',levels,'level');renderChips('#equipmentFilters',equipment,'equipment');const q=$('#exerciseSearch').value.trim().toLowerCase();const list=EXERCISES.filter(e=>(filters.body==='Todos'||e.body===filters.body)&&(filters.level==='Todos'||e.level===levelMap[filters.level])&&(filters.equipment==='Todos'||e.equipment===eqMap[filters.equipment])&&(!q||`${e.name} ${e.body} ${e.target}`.toLowerCase().includes(q)));$('#exerciseResultCount').textContent=`${list.length}`;$('#exerciseGrid').innerHTML=list.map(e=>`<button class="exercise-card" data-id="${e.id}"><div class="thumb" data-media-id="${e.id}"><span class="media-spinner"></span></div><div><b>${escapeHTML(e.name)}</b><small>${e.body} • ${e.type==='time'?targetFor(e)+'s':targetFor(e)+' reps'} • ${LABELS.level[e.level]}${progressLabel(e)!=='Base'?` • ${progressLabel(e)}`:''}</small></div></button>`).join('')||'<div class="empty" style="grid-column:1/-1">Nenhum exercício encontrado com esses filtros.</div>';
  await Promise.all(list.map(async e=>{const card=$(`.exercise-card[data-id="${CSS.escape(e.id)}"] .thumb`);if(!card)return;const urls=await resolveMediaCandidates(e);let i=0;const tryNext=()=>{if(i>=urls.length){card.innerHTML='<span>GIF indisponível</span>';return}const url=urls[i++];const img=new Image();img.loading='lazy';img.alt=`Demonstração de ${e.name}`;img.onload=()=>{card.innerHTML='';card.appendChild(img)};img.onerror=tryNext;img.src=url};tryNext()}));
  $$('.exercise-card').forEach(b=>b.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('exercise:detail',{detail:{id:b.dataset.id}}))));
}
function renderChips(selector,items,key){$(selector).innerHTML=items.map(x=>`<button class="chip ${filters[key]===x?'active':''}" data-filter-key="${key}" data-value="${x}">${x}</button>`).join('');$$(`${selector} .chip`).forEach(b=>b.addEventListener('click',()=>{filters[key]=b.dataset.value;renderDiscover()}))}
export function initDiscover(){$('#exerciseSearch').addEventListener('input',renderDiscover);renderDiscover()}
