import {APP,LABELS} from '../config.js';import {EXERCISES} from '../data/exercises.js';import {$,formatSeconds} from '../core/utils.js';import {state} from '../core/state.js';import {buildWorkout,compatible,targetFor,recommendedSplit} from '../services/personalization.js';import {WorkoutEngine} from '../services/workout-engine.js';
let engine=null;let prepTimer=null;let holdTimer=null;let restTimer=null;let soundOn=true;
function clearTimers(){clearInterval(prepTimer);clearInterval(holdTimer);clearInterval(restTimer)}
export function startWorkout(split=recommendedSplit(),custom=null){clearTimers();engine=new WorkoutEngine(custom?[{...custom,target:targetFor(custom)}]:buildWorkout(split),split);$('#workoutModal').classList.remove('hidden');showPrep()}
function showPrep(){$('#prepScreen').classList.remove('hidden');$('#workoutStage').classList.add('hidden');let n=APP.prepSeconds;$('#prepCount').textContent=n;$('#prepProgress').style.width='0%';$('.prep-ring')?.style.setProperty('--prep-angle','0deg');prepTimer=setInterval(()=>{n--;$('#prepCount').textContent=n;const pct=(APP.prepSeconds-n)/APP.prepSeconds;$('#prepProgress').style.width=`${pct*100}%`;$('.prep-ring')?.style.setProperty('--prep-angle',`${pct*360}deg`);if(n<=0){clearInterval(prepTimer);$('#prepScreen').classList.add('hidden');$('#workoutStage').classList.remove('hidden');renderExercise()}},1000)}
function renderExercise(){clearTimers();const e=engine.current;if(!e)return;$('#workoutCounter').textContent=`${engine.index+1}/${engine.items.length}`;$('#workoutName').textContent=engine.split==='CUSTOM'?'Exercício livre':(engine.split==='A'?'Peito • Ombros • Tríceps':engine.split==='B'?'Costas • Bíceps':engine.split==='C'?'Pernas • Glúteos • Core':'Corpo inteiro');$('#workoutProgress').style.width=`${(engine.index/Math.max(1,engine.items.length))*100}%`;$('#workoutType').textContent=engine.isWarmup?'AQUECIMENTO':engine.isCooldown?'FINALIZAÇÃO':'TREINO';$('#workoutTitle').textContent=e.name;$('#workoutSubtitle').textContent=e.desc;const media=e.media||'';const isVideo=/\.(mp4|webm|mov)(\?|$)/i.test(media);$('#exerciseMedia').innerHTML=media?(isVideo?`<video class="exercise-video" src="${media}" autoplay muted loop playsinline preload="metadata" poster="${e.poster||''}"></video>`:`<img class="exercise-gif" src="${media}" alt="Demonstração de ${e.name}" loading="eager">`):`<div class="media-placeholder"><strong>▶</strong><span>Demonstração desta variação ainda não cadastrada.</span></div>`;const mediaEl=$('#exerciseMedia').querySelector('img,video');if(mediaEl)mediaEl.addEventListener('error',()=>{if(e.poster){mediaEl.outerHTML=`<img class="exercise-fallback" src="${e.poster}" alt="Demonstração de ${e.name}">`}else{$('#exerciseMedia').innerHTML=`<div class="media-placeholder"><strong>▶</strong><span>Mídia indisponível no momento.</span></div>`}});$('#setLabel').textContent=`SÉRIE ${engine.set} DE ${e.sets}`;$('#targetLabel').textContent=e.type==='time'?`${e.target} segundos`:`${e.target} repetições`;$('#repCounter').classList.toggle('hidden',e.type!=='reps');$('#holdTimer').classList.toggle('hidden',e.type!=='time');$('#restBox').classList.add('hidden');$('#workoutNext').disabled=false;$('#workoutNext').textContent=e.type==='time'?'Iniciar exercício →':'Concluir série →';$('#skipExercise').textContent=engine.isCooldown?'Pular alongamento':'Pular exercício';if(e.type==='reps'){$('#repDone').textContent=engine.done;$('#repGoal').textContent=e.target}else startHold(e.target)}
function startHold(seconds){let n=seconds;$('#holdTimer').textContent=formatSeconds(n);$('#workoutNext').disabled=true;$('#workoutNext').onclick=()=>{if($('#workoutNext').dataset.holdDone!=='1'){return finishHold()}};$('#workoutNext').dataset.holdDone='0';holdTimer=setInterval(()=>{n--;$('#holdTimer').textContent=formatSeconds(n);if(n<=0){clearInterval(holdTimer);$('#workoutNext').dataset.holdDone='1';$('#workoutNext').disabled=false;$('#workoutNext').textContent='Concluir série →'}},1000)}
function finishHold(){clearInterval(holdTimer);$('#workoutNext').dataset.holdDone='1';$('#workoutNext').textContent='Concluir série →';advance()}
function advance(){if(!engine||!engine.current)return;if(engine.current.type==='reps'&&engine.done<engine.current.target){engine.done=engine.current.target;$('#repDone').textContent=engine.done}const result=engine.finishSet();if(result.done){window.dispatchEvent(new CustomEvent('workout:finished',{detail:engine.result}));return}if(result.rest){showRest(result.rest)}else renderExercise()}
function showRest(seconds){clearInterval(restTimer);$('#restBox').classList.remove('hidden');$('#repCounter').classList.add('hidden');$('#holdTimer').classList.add('hidden');$('#workoutNext').disabled=true;let n=seconds;$('#restTimer').textContent=formatSeconds(n);restTimer=setInterval(()=>{n--;$('#restTimer').textContent=formatSeconds(Math.max(0,n));if(n<=0){clearInterval(restTimer);$('#restBox').classList.add('hidden');renderExercise()}},1000)}
function replace(){const current=engine.current;const pool=EXERCISES.filter(e=>e.body===current.body&&e.id!==current.id&&compatible(e));if(!pool.length){window.dispatchEvent(new CustomEvent('toast',{detail:'Não há outra opção compatível para este grupo.'}));return}const next=pool[Math.floor(Math.random()*pool.length)];engine.replace({...next,target:targetFor(next)});renderExercise()}
export function initWorkout(){ $('#closeWorkout').onclick=()=>{clearTimers();$('#workoutModal').classList.add('hidden')};$('#cancelPreparation').onclick=()=>{$('#closeWorkout').click()};$('#repMinus').onclick=()=>{$('#repDone').textContent=engine.changeRep(-1)};$('#repPlus').onclick=()=>{$('#repDone').textContent=engine.changeRep(1)};$('#workoutNext').onclick=advance;$('#replaceExercise').onclick=replace;$('#skipExercise').onclick=()=>{if(engine.skip())window.dispatchEvent(new CustomEvent('workout:finished',{detail:engine.result}));else renderExercise()};$('#skipRest').onclick=()=>{clearInterval(restTimer);$('#restBox').classList.add('hidden');renderExercise()};$('#soundToggle').onclick=()=>{soundOn=!soundOn;$('#soundToggle').classList.toggle('sound-off',!soundOn)}}
