import {EXERCISE_BY_ID} from '../data/exercises.js';import {SPLITS} from '../data/plans.js';import {LABELS} from '../config.js';import {state} from '../core/state.js';
const LEVEL={beginner:1,intermediate:2,advanced:3};
export function planSummary(){const goals=state.answers.goal||[];const names=goals.map(g=>LABELS.goal[g]).filter(Boolean);const map={hypertrophy:'Construtor de Massa',strength:'Força em Casa',calisthenics:'Calistenia Progressiva',conditioning:'Condicionamento em Casa',mobility:'Mobilidade em Casa'};return {name:goals.length===1?(map[goals[0]]||'Plano personalizado'):'Plano personalizado',desc:`Treinos combinando ${names.join(' + ')} de acordo com suas escolhas.`}}
export function hasEquipment(required){const have=state.answers.equipment||['none'];if(required==='none')return true;return have.includes(required)}
export function compatible(ex){return hasEquipment(ex.equipment)&&LEVEL[ex.level]<=LEVEL[state.answers.level]+1}
export function targetFor(ex){if(ex.type==='time')return Math.max(15,ex.base+(state.answers.level==='advanced'?10:state.answers.level==='intermediate'?5:0));return Math.max(5,ex.base+(state.answers.level==='advanced'?3:state.answers.level==='intermediate'?2:0))}
function focusIds(){const focus=state.answers.focus||['body'];if(focus.includes('mobility'))return ['hip-mobility','chest-stretch'];return []}
const SPLIT_FOCUS={A:['Peito','Ombros','Braços'],B:['Costas','Braços'],C:['Pernas','Glúteos','Core'],FULL:['Peito','Costas','Pernas','Glúteos','Core','Ombros']};
function isInSplit(ex,split){const plan=SPLITS[split]||SPLITS.FULL;return plan.ids.includes(ex.id)}
export function splitForFrequency(){const n=Number(state.answers.frequency);if(n===2)return ['FULL','FULL'];if(n>=4)return ['A','B','C','FULL'];return ['A','B','C']}
export function recommendedSplit(){const idx=Math.max(0,state.workouts%splitForFrequency().length);return splitForFrequency()[idx]}
export function buildWorkout(split){const plan=SPLITS[split]||SPLITS.FULL;const priority=focusIds();const ids=[...plan.ids,...priority];const selected=[];for(const id of ids){const e=EXERCISE_BY_ID[id];if(e&&compatible(e)&&!selected.some(x=>x.id===e.id)&&(isInSplit(e,split)||e.body==='Mobilidade'))selected.push(e)}if(!selected.length){for(const id of SPLITS.FULL.ids){const e=EXERCISE_BY_ID[id];if(e&&compatible(e))selected.push(e)}}const warm=['arm-circles','hip-mobility'].map(id=>EXERCISE_BY_ID[id]);const cool=(state.answers.focus||[]).includes('mobility')?['hip-mobility','chest-stretch']:['hip-mobility','quad-stretch'];return [...warm,...selected,...cool.map(id=>EXERCISE_BY_ID[id])].filter(Boolean).map(e=>({...e,target:targetFor(e)}))}
